ZadachaFinal2/Controllers/BigController.cs
using Microsoft.AspNetCore.Mvc;
using ZadachaFinal2.Data;

namespace ZadachaFinal2.Controllers
{
    public class BigController : Controller
    {
        protected ZadachaDbContext _db;
        public BigController(ZadachaDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var i = _db;
            return View(i);
        }
    }
}

ZadachaFinal2/Controllers/Zad1Controller.cs
using Microsoft.AspNetCore.Mvc;
using ZadachaFinal2.Data;
using ZadachaFinal2.Models;

namespace ZadachaFinal2.Controllers
{
    public class Zad1Controller : Controller
    {
        protected ZadachaDbContext _db;
        public Zad1Controller(ZadachaDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Zadacha1> zad1List = _db.zad1;
            return View(zad1List);
        }
        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Zadacha1 obj)
        {
            if (ModelState.IsValid)
            {
                _db.zad1.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if(id == null || id < 1) { return NotFound(); }
            var zad1 = _db.zad1.Find(id);
            if (zad1 == null) { return NotFound(); }
            return View(zad1);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Zadacha1 obj)
        {
            if (ModelState.IsValid)
            {
                _db.zad1.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id < 1) { return NotFound(); }
            var zad1 = _db.zad1.Find(id);
            if (zad1 == null) { return NotFound(); }
            return View(zad1);
        }

        //POST
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            if(id==null || id < 1) { return NotFound(); }
            var obj = _db.zad1.Find(id);
            _db.zad1.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

ZadachaFinal2/Controllers/Zad2Controller.cs
using Microsoft.AspNetCore.Mvc;
using ZadachaFinal2.Data;
using ZadachaFinal2.Models;

namespace ZadachaFinal2.Controllers
{
    public class Zad2Controller : Controller
    {
        protected ZadachaDbContext _db;
        public Zad2Controller(ZadachaDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Zadacha2> zad2List = _db.zad2;
            return View(zad2List);
        }

        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Zadacha2 obj)
        {
            if (ModelState.IsValid)
            {
                _db.zad2.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id < 1) { return NotFound(); }
            var zad2 = _db.zad2.Find(id);
            if (zad2 == null) { return NotFound(); }
            return View(zad2);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Zadacha2 obj)
        {
            if (ModelState.IsValid)
            {
                _db.zad2.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }


        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id < 1) { return NotFound(); }
            var zad2 = _db.zad2.Find(id);
            if (zad2 == null) { return NotFound(); }
            return View(zad2);
        }

        //POST
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            if(id == null || id < 1) { return NotFound(); }
            var obj = _db.zad2.Find(id);
            _db.zad2.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");  
            
        }
    }
}

ZadachaFinal2/Controllers/Zad3Controller.cs
using Microsoft.AspNetCore.Mvc;
using ZadachaFinal2.Data;
using ZadachaFinal2.Models;

namespace ZadachaFinal2.Controllers
{
    public class Zad3Controller : Controller
    {
        protected ZadachaDbContext _db;
        public Zad3Controller(ZadachaDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Zadacha3> zad3List = _db.zad3;
            return View(zad3List);
        }
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Zadacha3 obj)
        {
            if (ModelState.IsValid)
            {
                _db.zad3.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id < 1) { return NotFound(); }
            var zad3 = _db.zad3.Find(id);
            if (zad3 == null) { return NotFound(); }
            return View(zad3);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Zadacha3 obj)
        {
            if (ModelState.IsValid)
            {
                _db.zad3.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id < 1) { return NotFound(); }
            var zad3 = _db.zad3.Find(id);
            if (zad3 == null) { return NotFound(); }
            return View(zad3);
        }

        //POST
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            if(id == null || id < 1) { return NotFound(); }
            var obj = _db.zad3.Find(id);
            _db.zad3.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

ZadachaFinal2/Views/Shared/_Index.cshtml
<table class="table-bordered table-striped"style="width:100%">
    <thead>
        <tr>
            <th width="20%">
                Задача
            </th>
            <th width="30%">
                Описание
            </th>
            <th width="20%">
                Примерное
                время выполнения
            </th>
            <th width="15%">
                Сделано
            </th>
            <th width="15%"></th>
        </tr>
    </thead>
    <tbody>

ZadachaFinal2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ZadachaFinal2</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ZadachaFinal2.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-light" href="#">Строка навигации</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active text-white" asp-controller="Home" asp-action="Index">На главную страницу
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" asp-controller="Zad1" asp-action="Index">Задача 1</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" asp-controller="Zad2" asp-action="Index">Задача 2</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" asp-controller="Zad3" asp-action="Index">Задача 3</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" asp-controller="Big" asp-action="Index">Все задачи</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"></a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ZadachaFinal2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>